This prototype shows the code for the Data Scientist to get acces and download a dataset. 

First install syft, this will install the 0.6.0 version

In [2]:
!pip install syft

Import all the necessary dependencies

Now the Tusted Curator Teacher (DataScientist) will upload the dataset and train the model

In [3]:
import syft as sy
import pandas as pd
import numpy as np

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
df1 = pd.read_csv('/content/drive/MyDrive/df_entrenar_modelo.csv', index_col=0 )
df1

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
532            1       86             66             52       65  41.3   
533            6       91              0              0        0  29.8   
534            1       77             56             30       56  33.3   
535            4      132              0              0        0  32.9   
536            0      105             90              0        0  29.6   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
532                     0.917   29        0  
533                     0.501   31        0  
534                     1.251   24        0  
535                     0.302   23        1  
536                     0.197   46        0  

[537 rows x 9 columns]

In [60]:
df1.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [61]:
x = df1.iloc[:,0:8] # Features

In [62]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
532            1       86             66             52       65  41.3   
533            6       91              0              0        0  29.8   
534            1       77             56             30       56  33.3   
535            4      132              0              0        0  32.9   
536            0      105             90              0        0  29.6   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
532                     0.917   29  
533                     0.501   31  
534                     1.251   24  
535                     0.302   23  
536                     0.197   46  

[537 rows x 8 columns]

In [84]:
y = df1["Outcome"] # Lables

In [85]:
y

0      1
1      0
2      1
3      0
4      1
      ..
532    0
533    0
534    0
535    1
536    0
Name: Outcome, Length: 537, dtype: int64

In [86]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(x.values)

In [87]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0, n_jobs=-1).fit(X_scaled , y.values)     

With de User and Password the Data Scientist log to the domain 

In [89]:
# Logging into the domain as DS

DOMAIN_URL1 ="http://40.118.207.120:80"
domain = sy.login(
    url=DOMAIN_URL1,
    email="szanottag@gmail.com",
    password="passwordtest",
    port=8081
)

Connecting to http://40.118.207.120:80... done! 	 Logging into node... done!


List the Dataset in order to check that it has been correctly created

In [90]:
domain.datasets

Check the structure of the Dataset

In [91]:
domain.datasets[0]

Dataset: diabetes_consultas
Description: Diabetes_Consultas



In this case, the information is storage as a variable called "mydata" 

In [92]:
mydata = domain.datasets[0]

Lets check "mydata"

In [93]:
mydata

Dataset: diabetes_consultas
Description: Diabetes_Consultas



In [94]:
mydata["data"]

<TensorPointer -> node:0188a01ab220455f93c75b1eb82ce0c6>

if the Data Scientist try to download the dataset pysyft protect the information and give the following message "You do not have permission to .get()"

In [95]:
ptr = domain.datasets[0]["data"]

In [96]:
data_tensor = ptr.get()

[2022-03-13T23:29:07.424648+0000][CRITICAL][logger]][62] You do not have permission to .get() Object with ID: <UID: 0188a01ab220455f93c75b1eb82ce0c6> on node node Please submit a request.


AuthorizationException: ignored

Pysyft allow to request permission and give a reason to the Data Owner 

In [97]:
ptr.request(reason="Para salvar la tesis")

Lets check the request 

In [98]:
domain.requests

[<RequestMessage: 4a5f513439154d91a1093651db2ea51d>]

With the request accepted by the Data Owner, the Data Scientist has the possibilty to download the information

In [99]:
data_tensor = ptr.get()

Lets check the information downloaded

In [100]:
data_tensor

Tensor(child=RowEntityPhiTensor(child=[SingleEntityPhiTensor(entity=0, child=[[ 0 57 60  0  0 21  0 67]]), SingleEntityPhiTensor(entity=1, child=[[  0 127  80  37 210  36   0  23]]), SingleEntityPhiTensor(entity=2, child=[[  3 129  92  49 155  36   0  32]]), SingleEntityPhiTensor(entity=3, child=[[  8 100  74  40 215  39   0  43]]), SingleEntityPhiTensor(entity=4, child=[[  3 128  72  25 190  32   0  27]]), SingleEntityPhiTensor(entity=5, child=[[10 90 85 32  0 34  0 56]]), SingleEntityPhiTensor(entity=6, child=[[ 4 84 90 23 56 39  0 25]]), SingleEntityPhiTensor(entity=7, child=[[ 1 88 78 29 76 32  0 29]]), SingleEntityPhiTensor(entity=8, child=[[  8 186  90  35 225  34   0  37]]), SingleEntityPhiTensor(entity=9, child=[[  5 187  76  27 207  43   1  53]]), SingleEntityPhiTensor(entity=10, child=[[  4 131  68  21 166  33   0  28]]), SingleEntityPhiTensor(entity=11, child=[[  1 164  82  43  67  32   0  50]]), SingleEntityPhiTensor(entity=12, child=[[  4 189 110  31   0  28   0  37]]), Si

In [101]:
data_tensor.child.child

[SingleEntityPhiTensor(entity=0, child=[[ 0 57 60  0  0 21  0 67]]),
 SingleEntityPhiTensor(entity=1, child=[[  0 127  80  37 210  36   0  23]]),
 SingleEntityPhiTensor(entity=2, child=[[  3 129  92  49 155  36   0  32]]),
 SingleEntityPhiTensor(entity=3, child=[[  8 100  74  40 215  39   0  43]]),
 SingleEntityPhiTensor(entity=4, child=[[  3 128  72  25 190  32   0  27]]),
 SingleEntityPhiTensor(entity=5, child=[[10 90 85 32  0 34  0 56]]),
 SingleEntityPhiTensor(entity=6, child=[[ 4 84 90 23 56 39  0 25]]),
 SingleEntityPhiTensor(entity=7, child=[[ 1 88 78 29 76 32  0 29]]),
 SingleEntityPhiTensor(entity=8, child=[[  8 186  90  35 225  34   0  37]]),
 SingleEntityPhiTensor(entity=9, child=[[  5 187  76  27 207  43   1  53]]),
 SingleEntityPhiTensor(entity=10, child=[[  4 131  68  21 166  33   0  28]]),
 SingleEntityPhiTensor(entity=11, child=[[  1 164  82  43  67  32   0  50]]),
 SingleEntityPhiTensor(entity=12, child=[[  4 189 110  31   0  28   0  37]]),
 SingleEntityPhiTensor(entit

The information is organized into rows with different levels.

The Data Scientist has to extract and recreate the original dataset.

In [102]:
values = list(map(lambda x: x.child[0], data_tensor.child.child))

In [103]:
values

[array([ 0, 57, 60,  0,  0, 21,  0, 67], dtype=int32),
 array([  0, 127,  80,  37, 210,  36,   0,  23], dtype=int32),
 array([  3, 129,  92,  49, 155,  36,   0,  32], dtype=int32),
 array([  8, 100,  74,  40, 215,  39,   0,  43], dtype=int32),
 array([  3, 128,  72,  25, 190,  32,   0,  27], dtype=int32),
 array([10, 90, 85, 32,  0, 34,  0, 56], dtype=int32),
 array([ 4, 84, 90, 23, 56, 39,  0, 25], dtype=int32),
 array([ 1, 88, 78, 29, 76, 32,  0, 29], dtype=int32),
 array([  8, 186,  90,  35, 225,  34,   0,  37], dtype=int32),
 array([  5, 187,  76,  27, 207,  43,   1,  53], dtype=int32),
 array([  4, 131,  68,  21, 166,  33,   0,  28], dtype=int32),
 array([  1, 164,  82,  43,  67,  32,   0,  50], dtype=int32),
 array([  4, 189, 110,  31,   0,  28,   0,  37], dtype=int32),
 array([  1, 116,  70,  28,   0,  27,   0,  21], dtype=int32),
 array([  3,  84,  68,  30, 106,  31,   0,  25], dtype=int32),
 array([  6, 114,  88,   0,   0,  27,   0,  66], dtype=int32),
 array([ 1, 88, 62, 24, 

Lets check the DataFrame

In [108]:
df2 = pd.DataFrame(values)
df2

0    1   2   3    4   5  6   7
0     0   57  60   0    0  21  0  67
1     0  127  80  37  210  36  0  23
2     3  129  92  49  155  36  0  32
3     8  100  74  40  215  39  0  43
4     3  128  72  25  190  32  0  27
..   ..  ...  ..  ..  ...  .. ..  ..
226  10  101  76  48  180  32  0  63
227   2  122  70  27    0  36  0  27
228   5  121  72  23  112  26  0  30
229   1  126  60   0    0  30  0  47
230   1   93  70  31    0  30  0  23

[231 rows x 8 columns]

In [109]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df2.values) 

In [110]:
from sklearn.linear_model import LogisticRegression

prediccion = clf.predict(X_scaled)    
prediccion

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In [111]:
df_prediccion = pd.DataFrame(prediccion, columns=["prediccion"])

In [112]:
df_prediccion

prediccion
0             0
1             0
2             0
3             0
4             0
..          ...
226           0
227           0
228           0
229           0
230           0

[231 rows x 1 columns]

In [113]:
df_prediccion.to_csv("df_prediccion.csv")
df_prediccion.to_csv("/content/drive/MyDrive/df_prediccion.csv")