This prototype shows the code for the Data Owner (Trusted Curator Teacher) to upload a dataset with the predictions and give access to a Data Scientist (Trusted Curator Student)

First install syft, this will install the 0.6.0 version


In [1]:
!pip install syft

Import all the necessary dependencies

Now the Tusted Curator Student (DataScientist) will download the dataset

With de User and Password the Data Scientist log to the domain 

In [2]:
import syft as sy
from google.colab import files
import pandas as pd
import numpy as np

In [5]:
# Logging into the domain as DS

DOMAIN_URL2 ="http://ort.westus.cloudapp.azure.com:80"
domain = sy.login(
    url=DOMAIN_URL2,
    email="jramas@gmail.com",
    password="orttest2"
)


Connecting to http://ort.westus.cloudapp.azure.com:80... done! 	 Logging into node... done!


List the Dataset in order to check that it has been correctly created

In [6]:
domain.datasets

Check the structure of the Dataset

In [7]:
domain.datasets[7]

Dataset: diabetes_prediccion
Description: Diabetes_Prediccion



In this case, the information is storage as a variable called "mydata" 

In [8]:
mydata = domain.datasets[7]

Lets check "mydata"

In [9]:
mydata

Dataset: diabetes_prediccion
Description: Diabetes_Prediccion



In [10]:
mydata["data"]

<TensorPointer -> node:4242a88d43ba43199bd1b646c308a291>

if the Data Scientist try to download the dataset pysyft protect the information and give the following message "You do not have permission to .get()"

In [11]:
ptr = domain.datasets[7]["data"]

Pysyft allow to request permission and give a reason to the Data Owner 

In [12]:
data_tensor = ptr.get()

[2022-03-14T00:36:13.656105+0000][CRITICAL][logger]][1642] You do not have permission to .get() Object with ID: <UID: 4242a88d43ba43199bd1b646c308a291> on node node Please submit a request.


AuthorizationException: ignored

In [13]:
ptr.request(reason="para ver la prediccion")

Lets check the request 

In [14]:
domain.requests

[<RequestMessage: f64a5d52305540c48d01fb755b7d4f0b>, <RequestMessage: 1d22e0d181ff43cb880f60360290ef7e>, <RequestMessage: d7eae0de20aa4e029fd4b6bc34eacc34>, <RequestMessage: 57482cd372174a6cba95406ba3085c7e>, <RequestMessage: d6910261c49b48179b15234795caed3d>, <RequestMessage: 3d429fca4da6446a9f141e0f8977a5d2>, <RequestMessage: 0187881026ce46b28926c3244ab4c3c8>, <RequestMessage: db990a5d0e874f16a5071db82cf4d40f>, <RequestMessage: f72e6230604444b29a70ca7e42cbf227>]

With the request accepted by the Data Owner (Trusted Curator Teacher), the Data Scientist has the possibilty to download the information

In [15]:
data_tensor = ptr.get()

Lets check the information downloaded

In [16]:
data_tensor

Tensor(child=RowEntityPhiTensor(child=[SingleEntityPhiTensor(entity=0, child=[[0]]), SingleEntityPhiTensor(entity=1, child=[[0]]), SingleEntityPhiTensor(entity=2, child=[[0]]), SingleEntityPhiTensor(entity=3, child=[[0]]), SingleEntityPhiTensor(entity=4, child=[[0]]), SingleEntityPhiTensor(entity=5, child=[[0]]), SingleEntityPhiTensor(entity=6, child=[[0]]), SingleEntityPhiTensor(entity=7, child=[[0]]), SingleEntityPhiTensor(entity=8, child=[[1]]), SingleEntityPhiTensor(entity=9, child=[[1]]), SingleEntityPhiTensor(entity=10, child=[[0]]), SingleEntityPhiTensor(entity=11, child=[[1]]), SingleEntityPhiTensor(entity=12, child=[[1]]), SingleEntityPhiTensor(entity=13, child=[[0]]), SingleEntityPhiTensor(entity=14, child=[[0]]), SingleEntityPhiTensor(entity=15, child=[[0]]), SingleEntityPhiTensor(entity=16, child=[[0]]), SingleEntityPhiTensor(entity=17, child=[[0]]), SingleEntityPhiTensor(entity=18, child=[[0]]), SingleEntityPhiTensor(entity=19, child=[[0]]), SingleEntityPhiTensor(entity=20

In [17]:
data_tensor.child.child

[SingleEntityPhiTensor(entity=0, child=[[0]]),
 SingleEntityPhiTensor(entity=1, child=[[0]]),
 SingleEntityPhiTensor(entity=2, child=[[0]]),
 SingleEntityPhiTensor(entity=3, child=[[0]]),
 SingleEntityPhiTensor(entity=4, child=[[0]]),
 SingleEntityPhiTensor(entity=5, child=[[0]]),
 SingleEntityPhiTensor(entity=6, child=[[0]]),
 SingleEntityPhiTensor(entity=7, child=[[0]]),
 SingleEntityPhiTensor(entity=8, child=[[1]]),
 SingleEntityPhiTensor(entity=9, child=[[1]]),
 SingleEntityPhiTensor(entity=10, child=[[0]]),
 SingleEntityPhiTensor(entity=11, child=[[1]]),
 SingleEntityPhiTensor(entity=12, child=[[1]]),
 SingleEntityPhiTensor(entity=13, child=[[0]]),
 SingleEntityPhiTensor(entity=14, child=[[0]]),
 SingleEntityPhiTensor(entity=15, child=[[0]]),
 SingleEntityPhiTensor(entity=16, child=[[0]]),
 SingleEntityPhiTensor(entity=17, child=[[0]]),
 SingleEntityPhiTensor(entity=18, child=[[0]]),
 SingleEntityPhiTensor(entity=19, child=[[0]]),
 SingleEntityPhiTensor(entity=20, child=[[0]]),
 S

The information is organized into rows with different levels.

The Data Scientist has to extract and recreate the original dataset.

In [18]:
values = list(map(lambda x: x.child[0], data_tensor.child.child))

In [19]:
values

[array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([1], dtype=int32),
 array([1], dtype=int32),
 array([0], dtype=int32),
 array([1], dtype=int32),
 array([1], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([1], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([1], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], dtype=int32),
 array([0], 

Lets check the DataFrame

In [20]:
df_prediccion = pd.DataFrame(values, columns=["prediccion"])
df_prediccion

prediccion
0             0
1             0
2             0
3             0
4             0
..          ...
226           0
227           0
228           0
229           0
230           0

[231 rows x 1 columns]

Now the Trusted Curator Student can save the prediction from the Trusted Curator Teacher in a CSV.

In [21]:
df_prediccion.to_csv("df_prediccion_student.csv")
df_prediccion.to_csv("/content/drive/MyDrive/df_prediccion_student.csv")